---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-nodeport
  annotations:
    # service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    # service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/wp-login.php"
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
