apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ebs-vol
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: 
    fsType: ext4

